const hugeLevelDB = [
  { "left": "sin(x)^2 + cos(x)^2", "right": "1", "diff": 1 },
  { "left": "tan(x)", "right": "sin(x)/cos(x)", "diff": 1 },
  { "left": "cot(x)", "right": "cos(x)/sin(x)", "diff": 1 },
  { "left": "sec(x)", "right": "1/cos(x)", "diff": 1 },
  { "left": "csc(x)", "right": "1/sin(x)", "diff": 1 },
  { "left": "tan(x)*cot(x)", "right": "1", "diff": 1 },
  { "left": "sin(x)*csc(x)", "right": "1", "diff": 1 },
  { "left": "cos(x)*sec(x)", "right": "1", "diff": 1 },
  { "left": "1 + tan(x)^2", "right": "sec(x)^2", "diff": 1 },
  { "left": "1 + cot(x)^2", "right": "csc(x)^2", "diff": 1 },
  { "left": "sin(x)*sec(x)", "right": "tan(x)", "diff": 2 },
  { "left": "cos(x)*csc(x)", "right": "cot(x)", "diff": 2 },
  { "left": "(1-sin(x))*(1+sin(x))", "right": "cos(x)^2", "diff": 2 },
  { "left": "(1-cos(x))*(1+cos(x))", "right": "sin(x)^2", "diff": 2 },
  { "left": "sec(x)^2 - tan(x)^2", "right": "1", "diff": 2 },
  { "left": "csc(x)^2 - cot(x)^2", "right": "1", "diff": 2 },
  { "left": "sin(x) + sin(x)*cot(x)^2", "right": "csc(x)", "diff": 2 },
  { "left": "cos(x) + cos(x)*tan(x)^2", "right": "sec(x)", "diff": 2 },
  { "left": "sin(x)^2/cos(x) + cos(x)", "right": "sec(x)", "diff": 2 },
  { "left": "cos(x)^2/sin(x) + sin(x)", "right": "csc(x)", "diff": 2 },
  { "left": "(1 - sin(x)^2)/(1 - cos(x)^2)", "right": "cot(x)^2", "diff": 3 },
  { "left": "cos(x)^4 - sin(x)^4", "right": "cos(x)^2 - sin(x)^2", "diff": 3 },
  { "left": "sec(x)^4 - tan(x)^4", "right": "sec(x)^2 + tan(x)^2", "diff": 3 },
  { "left": "1/(sec(x) - tan(x))", "right": "sec(x) + tan(x)", "diff": 3 },
  { "left": "1/(csc(x) - cot(x))", "right": "csc(x) + cot(x)", "diff": 3 },
  { "left": "tan(x)/(sec(x) - 1)", "right": "(sec(x) + 1)/tan(x)", "diff": 3 },
  { "left": "cot(x)/(csc(x) - 1)", "right": "(csc(x) + 1)/cot(x)", "diff": 3 },
  { "left": "sin(x)^3 + sin(x)*cos(x)^2", "right": "sin(x)", "diff": 3 },
  { "left": "1/(1-sin(x)) + 1/(1+sin(x))", "right": "2*sec(x)^2", "diff": 3 },
  { "left": "cos(x)/(1-sin(x)) - cos(x)/(1+sin(x))", "right": "2*tan(x)", "diff": 3 },
  { "left": "(sin(x) + cos(x))^2 + (sin(x) - cos(x))^2", "right": "2", "diff": 4 },
  { "left": "(tan(x) + cot(x))/(sec(x)*csc(x))", "right": "1", "diff": 4 },
  { "left": "(sec(x) + tan(x))/(cos(x) + cot(x))", "right": "sec(x)*tan(x)", "diff": 4 },
  { "left": "(1-tan(x)^2)/(1+tan(x)^2)", "right": "cos(x)^2 - sin(x)^2", "diff": 4 },
  { "left": "(sec(x) - 1)/(sec(x) + 1)", "right": "(1-cos(x))/(1+cos(x))", "diff": 4 },
  { "left": "cot(x)^2 - cos(x)^2", "right": "cot(x)^2 * cos(x)^2", "diff": 4 },
  { "left": "tan(x)^2 - sin(x)^2", "right": "tan(x)^2 * sin(x)^2", "diff": 4 },
  { "left": "(sin(x) + cos(x))/sin(x)", "right": "1 + cot(x)", "diff": 4 },
  { "left": "tan(x)^2/(sec(x) + 1)", "right": "sec(x) - 1", "diff": 4 },
  { "left": "(cos(x)^3 + sin(x)^3)/(cos(x) + sin(x))", "right": "1 - sin(x)*cos(x)", "diff": 4 },
  { "left": "sin(2*x)", "right": "2*tan(x)/(1+tan(x)^2)", "diff": 5 },
  { "left": "cos(2*x)", "right": "(1-tan(x)^2)/(1+tan(x)^2)", "diff": 5 },
  { "left": "tan(2*x)", "right": "2*tan(x)/(1-tan(x)^2)", "diff": 5 },
  { "left": "sin(2*x)/(1+cos(2*x))", "right": "tan(x)", "diff": 5 },
  { "left": "(1-cos(2*x))/sin(2*x)", "right": "tan(x)", "diff": 5 },
  { "left": "(1-cos(2*x))/(1+cos(2*x))", "right": "tan(x)^2", "diff": 5 },
  { "left": "sin(3*x)", "right": "3*sin(x) - 4*sin(x)^3", "diff": 5 },
  { "left": "cos(3*x)", "right": "4*cos(x)^3 - 3*cos(x)", "diff": 5 },
  { "left": "(sin(x/2) + cos(x/2))^2", "right": "1 + sin(x)", "diff": 5 },
  { "left": "tan(x/2)", "right": "csc(x) - cot(x)", "diff": 5 },
  { "left": "sin(x+y)*sin(x-y)", "right": "sin(x)^2 - sin(y)^2", "diff": 6 },
  { "left": "cos(x+y)*cos(x-y)", "right": "cos(x)^2 - sin(y)^2", "diff": 6 },
  { "left": "tan(x+y) - tan(x) - tan(y)", "right": "tan(x+y)*tan(x)*tan(y)", "diff": 6 },
  { "left": "sin(x+y)/(cos(x)*cos(y))", "right": "tan(x) + tan(y)", "diff": 6 },
  { "left": "cos(x-y)/(cos(x)*sin(y))", "right": "tan(x) + cot(y)", "diff": 6 },
  { "left": "sin(x+pi/4) + cos(x+pi/4)", "right": "sqrt(2)*cos(x)", "diff": 6 },
  { "left": "tan(x+y)/cot(x-y)", "right": "(tan(x)^2 - tan(y)^2)/(1 - tan(x)^2 * tan(y)^2)", "diff": 6 },
  { "left": "sin(x) + cos(x)", "right": "sqrt(2)*sin(x + pi/4)", "diff": 6 },
  { "left": "cot(x+y)", "right": "(cot(x)*cot(y) - 1)/(cot(x) + cot(y))", "diff": 6 },
  { "left": "cos(x) + cos(x + 2*pi/3) + cos(x + 4*pi/3)", "right": "0", "diff": 6 },
  { "left": "sin(4*x)", "right": "4*sin(x)*cos(x)*(1 - 2*sin(x)^2)", "diff": 7 },
  { "left": "cos(4*x)", "right": "8*cos(x)^4 - 8*cos(x)^2 + 1", "diff": 7 },
  { "left": "sin(x) + sin(3*x) + sin(5*x)", "right": "(sin(3*x)^2)/sin(x)", "diff": 7 },
  { "left": "cos(x)*cos(2*x)*cos(4*x)", "right": "sin(8*x)/(8*sin(x))", "diff": 7 },
  { "left": "tan(x) + 2*tan(2*x) + 4*tan(4*x) + 8*cot(8*x)", "right": "cot(x)", "diff": 7 },
  { "left": "sin(x)^6 + cos(x)^6", "right": "1 - 3/4 * sin(2*x)^2", "diff": 7 },
  { "left": "sin(pi/9)*sin(2*pi/9)*sin(4*pi/9)", "right": "sqrt(3)/8", "diff": 7 },
  { "left": "cos(pi/9)*cos(2*pi/9)*cos(4*pi/9)", "right": "1/8", "diff": 7 },
  { "left": "tan(pi/9)*tan(2*pi/9)*tan(4*pi/9)", "right": "sqrt(3)", "diff": 7 },
  { "left": "(sin(x) + sin(3*x) + sin(5*x) + sin(7*x))/(cos(x) + cos(3*x) + cos(5*x) + cos(7*x))", "right": "tan(4*x)", "diff": 7 },
  { "left": "sin(2*A) + sin(2*B) + sin(2*C)", "right": "4*sin(A)*sin(B)*sin(C)", "diff": 8 },
  { "left": "cos(A) + cos(B) + cos(C)", "right": "1 + 4*sin(A/2)*sin(B/2)*sin(C/2)", "diff": 8 },
  { "left": "tan(A) + tan(B) + tan(C)", "right": "tan(A)*tan(B)*tan(C)", "diff": 8 },
  { "left": "cot(A/2) + cot(B/2) + cot(C/2)", "right": "cot(A/2)*cot(B/2)*cot(C/2)", "diff": 8 },
  { "left": "cos(pi/5)*cos(2*pi/5)", "right": "1/4", "diff": 8 },
  { "left": "prod([sin(k*pi/n) for k in range(1, n)])", "right": "n/2^(n-1)", "diff": 8 },
  { "left": "sec(x) + sec(x+2*pi/3) + sec(x+4*pi/3)", "right": "-3*sec(3*x)", "diff": 8 },
  { "left": "tan(pi/7)^2 + tan(2*pi/7)^2 + tan(3*pi/7)^2", "right": "21", "diff": 8 },
  { "left": "cos(pi/8)^4 + cos(3*pi/8)^4 + cos(5*pi/8)^4 + cos(7*pi/8)^4", "right": "3/2", "diff": 8 },
  { "left": "sin(theta)", "right": "theta * prod([1 - theta^2/(k^2 * pi^2) for k in range(1, 1000)])", "diff": 8 }
];
